// Code generated by odin-api-gen. DO NOT EDIT.
// Source: openapi.json — tag "Events"
package pocketsmith

import "core:fmt"

// Get event
//
// Gets a particular event by its ID.
get_event :: proc(
	c: ^Client,
	id: string,
	allocator := context.allocator,
) -> (result: Event, err: Error) {
	path := fmt.tprintf("/events/%v", id)
	resp := _execute(c, "GET", path, "", nil, allocator) or_return
	defer delete(resp.body, allocator)
	result = _decode(Event, resp.body, allocator) or_return
	return
}

// Update event
//
// Updates an event by its ID.
update_event :: proc(
	c: ^Client,
	id: string,
	body: Update_Event_Body,
	allocator := context.allocator,
) -> (result: Event, err: Error) {
	body_data := _encode(body, allocator) or_return
	path := fmt.tprintf("/events/%v", id)
	resp := _execute(c, "PUT", path, "", body_data, allocator) or_return
	defer delete(resp.body, allocator)
	result = _decode(Event, resp.body, allocator) or_return
	return
}

// Delete event
//
// Deletes an event by its ID.
delete_event :: proc(
	c: ^Client,
	id: string,
	behaviour: string,
	allocator := context.allocator,
) -> (err: Error) {
	qb: _Query_Builder
	_qb_init(&qb)
	_qb_add_string(&qb, "behaviour", behaviour)
	path := fmt.tprintf("/events/%v", id)
	resp := _execute(c, "DELETE", path, _qb_string(&qb), nil, allocator) or_return
	delete(resp.body, allocator)
	return
}

// List events in scenario.
//
// Lists events belonging to a scenario by their ID.
list_events_in_scenario :: proc(
	c: ^Client,
	id: i64,
	start_date: string,
	end_date: string,
	allocator := context.allocator,
) -> (result: []Event, err: Error) {
	qb: _Query_Builder
	_qb_init(&qb)
	_qb_add_string(&qb, "start_date", start_date)
	_qb_add_string(&qb, "end_date", end_date)
	path := fmt.tprintf("/scenarios/%v/events", id)
	resp := _execute(c, "GET", path, _qb_string(&qb), nil, allocator) or_return
	defer delete(resp.body, allocator)
	result = _decode([]Event, resp.body, allocator) or_return
	return
}

// Create event in scenario
//
// Creates an event in a scenario by its ID.
create_event_in_scenario :: proc(
	c: ^Client,
	id: i64,
	body: Create_Event_In_Scenario_Body,
	allocator := context.allocator,
) -> (result: Event, err: Error) {
	body_data := _encode(body, allocator) or_return
	path := fmt.tprintf("/scenarios/%v/events", id)
	resp := _execute(c, "POST", path, "", body_data, allocator) or_return
	defer delete(resp.body, allocator)
	result = _decode(Event, resp.body, allocator) or_return
	return
}

// List events in user.
//
// Lists events belonging to a user by their ID.
list_events_in_user :: proc(
	c: ^Client,
	id: i64,
	start_date: string,
	end_date: string,
	allocator := context.allocator,
) -> (result: []Event, err: Error) {
	qb: _Query_Builder
	_qb_init(&qb)
	_qb_add_string(&qb, "start_date", start_date)
	_qb_add_string(&qb, "end_date", end_date)
	path := fmt.tprintf("/users/%v/events", id)
	resp := _execute(c, "GET", path, _qb_string(&qb), nil, allocator) or_return
	defer delete(resp.body, allocator)
	result = _decode([]Event, resp.body, allocator) or_return
	return
}
