// Code generated by odin-api-gen. DO NOT EDIT.
// Source: openapi.json — tag "Attachments"
package pocketsmith

import "core:fmt"

// Optional query parameters for list_attachments_in_user.
List_Attachments_In_User_Options :: struct {
	// If set, returns unassigned attachments, that are available for assigning to a transaction.
	unassigned: Maybe(i64),
}

// Get attachment
//
// Gets a particular attachment by its ID.
get_attachment :: proc(
	c: ^Client,
	id: i64,
	allocator := context.allocator,
) -> (result: Attachment, err: Error) {
	path := fmt.tprintf("/attachments/%v", id)
	resp := _execute(c, "GET", path, "", nil, allocator) or_return
	defer delete(resp.body, allocator)
	result = _decode(Attachment, resp.body, allocator) or_return
	return
}

// Update attachment
//
// Updates the title of the attachment.
update_attachment :: proc(
	c: ^Client,
	id: i64,
	body: Update_Attachment_Body,
	allocator := context.allocator,
) -> (result: Attachment, err: Error) {
	body_data := _encode(body, allocator) or_return
	path := fmt.tprintf("/attachments/%v", id)
	resp := _execute(c, "PUT", path, "", body_data, allocator) or_return
	defer delete(resp.body, allocator)
	result = _decode(Attachment, resp.body, allocator) or_return
	return
}

// Delete attachment
//
// Deletes a particular attachment by its ID.
delete_attachment :: proc(
	c: ^Client,
	id: i64,
	allocator := context.allocator,
) -> (err: Error) {
	path := fmt.tprintf("/attachments/%v", id)
	resp := _execute(c, "DELETE", path, "", nil, allocator) or_return
	delete(resp.body, allocator)
	return
}

// List attachments in transaction
//
// Lists attachments belonging to a transaction by their ID.
list_attachments_in_transaction :: proc(
	c: ^Client,
	id: i64,
	allocator := context.allocator,
) -> (result: []Attachment, err: Error) {
	path := fmt.tprintf("/transactions/%v/attachments", id)
	resp := _execute(c, "GET", path, "", nil, allocator) or_return
	defer delete(resp.body, allocator)
	result = _decode([]Attachment, resp.body, allocator) or_return
	return
}

// Assigns attachment to transaction
//
// Assigns an attachment to the transaction by their ID.
assign_attachment_to_transaction :: proc(
	c: ^Client,
	id: i64,
	body: Assign_Attachment_To_Transaction_Body,
	allocator := context.allocator,
) -> (result: Attachment, err: Error) {
	body_data := _encode(body, allocator) or_return
	path := fmt.tprintf("/transactions/%v/attachments", id)
	resp := _execute(c, "POST", path, "", body_data, allocator) or_return
	defer delete(resp.body, allocator)
	result = _decode(Attachment, resp.body, allocator) or_return
	return
}

// Unassigns attachment in transaction
//
// Unassigns a particular attachment by its ID from the transaction ID. This does not delete the attachment, it only removes its association from the transaction.
unassign_attachment_in_transaction :: proc(
	c: ^Client,
	transaction_id: i64,
	attachment_id: i64,
	allocator := context.allocator,
) -> (err: Error) {
	path := fmt.tprintf("/transactions/%v/attachments/%v", transaction_id, attachment_id)
	resp := _execute(c, "DELETE", path, "", nil, allocator) or_return
	delete(resp.body, allocator)
	return
}

// Lists attachments in user
//
// Lists attachments belonging to a user by their ID.
list_attachments_in_user :: proc(
	c: ^Client,
	id: i64,
	opts := List_Attachments_In_User_Options{},
	allocator := context.allocator,
) -> (result: []Attachment, err: Error) {
	qb: _Query_Builder
	_qb_init(&qb)
	_qb_maybe_i64(&qb, "unassigned", opts.unassigned)
	path := fmt.tprintf("/users/%v/attachments", id)
	resp := _execute(c, "GET", path, _qb_string(&qb), nil, allocator) or_return
	defer delete(resp.body, allocator)
	result = _decode([]Attachment, resp.body, allocator) or_return
	return
}

// Create attachment in user
//
// Creates an attachment belonging to the user by their ID.
create_attachment_in_user :: proc(
	c: ^Client,
	id: i64,
	body: Create_Attachment_In_User_Body,
	allocator := context.allocator,
) -> (result: Attachment, err: Error) {
	body_data := _encode(body, allocator) or_return
	path := fmt.tprintf("/users/%v/attachments", id)
	resp := _execute(c, "POST", path, "", body_data, allocator) or_return
	defer delete(resp.body, allocator)
	result = _decode(Attachment, resp.body, allocator) or_return
	return
}
