// Code generated by odin-api-gen. DO NOT EDIT.
// Source: openapi.json — tag "Institutions"
package pocketsmith

import "core:fmt"

// Optional query parameters for delete_institution.
Delete_Institution_Options :: struct {
	// The unique identifier of the institution to merge into.
	merge_into_institution_id: Maybe(i64),
}

// Get institution
//
// Gets an institution by its ID.
get_institution :: proc(
	c: ^Client,
	id: i64,
	allocator := context.allocator,
) -> (result: Institution, err: Error) {
	path := fmt.tprintf("/institutions/%v", id)
	resp := _execute(c, "GET", path, "", nil, allocator) or_return
	defer delete(resp.body, allocator)
	result = _decode(Institution, resp.body, allocator) or_return
	return
}

// Update institution
//
// Updates the title and currency code for an institution.
update_institution :: proc(
	c: ^Client,
	id: i64,
	body: Update_Institution_Body,
	allocator := context.allocator,
) -> (result: Institution, err: Error) {
	body_data := _encode(body, allocator) or_return
	path := fmt.tprintf("/institutions/%v", id)
	resp := _execute(c, "PUT", path, "", body_data, allocator) or_return
	defer delete(resp.body, allocator)
	result = _decode(Institution, resp.body, allocator) or_return
	return
}

// Delete institution
//
// Deletes an institution and all data within. Alternatively, another institution can be provided to merge the data into to avoid losing it.
delete_institution :: proc(
	c: ^Client,
	id: i64,
	opts := Delete_Institution_Options{},
	allocator := context.allocator,
) -> (err: Error) {
	qb: _Query_Builder
	_qb_init(&qb)
	_qb_maybe_i64(&qb, "merge_into_institution_id", opts.merge_into_institution_id)
	path := fmt.tprintf("/institutions/%v", id)
	resp := _execute(c, "DELETE", path, _qb_string(&qb), nil, allocator) or_return
	delete(resp.body, allocator)
	return
}

// List institutions in user
//
// Lists all the institutions belonging to the user.
list_institutions_in_user :: proc(
	c: ^Client,
	id: i64,
	allocator := context.allocator,
) -> (result: []Institution, err: Error) {
	path := fmt.tprintf("/users/%v/institutions", id)
	resp := _execute(c, "GET", path, "", nil, allocator) or_return
	defer delete(resp.body, allocator)
	result = _decode([]Institution, resp.body, allocator) or_return
	return
}

// Create institution in user
//
// Creates an institution belonging to a user.
create_institution_in_user :: proc(
	c: ^Client,
	id: i64,
	body: Create_Institution_In_User_Body,
	allocator := context.allocator,
) -> (result: Institution, err: Error) {
	body_data := _encode(body, allocator) or_return
	path := fmt.tprintf("/users/%v/institutions", id)
	resp := _execute(c, "POST", path, "", body_data, allocator) or_return
	defer delete(resp.body, allocator)
	result = _decode(Institution, resp.body, allocator) or_return
	return
}
