// Code generated by odin-api-gen. DO NOT EDIT.
// Source: openapi.json — tag "Saved Searches"
package pocketsmith

import "core:fmt"

// List saved searches in user
//
// Lists saved searches belonging to a user by their ID.
list_saved_searches_in_user :: proc(
	c: ^Client,
	id: i64,
	allocator := context.allocator,
) -> (result: []Saved_Search, err: Error) {
	path := fmt.tprintf("/users/%v/saved_searches", id)
	resp := _execute(c, "GET", path, "", nil, allocator) or_return
	defer delete(resp.body, allocator)
	result = _decode([]Saved_Search, resp.body, allocator) or_return
	return
}
