// Code generated by odin-api-gen. DO NOT EDIT.
// Source: openapi.json — tag "Budgeting"
package pocketsmith

import "core:fmt"

// Optional query parameters for list_budget_for_user.
List_Budget_For_User_Options :: struct {
	// Whether parent categories should have their children rolled up into them. When used, the children will still appear in the collection on their own, but their actual and forecast figures will be rolled up to the root parent.
	roll_up: Maybe(bool),
}

// List budget for user
//
// Lists the user's budget, consisting of one or more budget analysis packages, one per category. Akin to the list on the Budget page in PocketSmith.
list_budget_for_user :: proc(
	c: ^Client,
	id: i64,
	opts := List_Budget_For_User_Options{},
	allocator := context.allocator,
) -> (result: []Budget_Analysis_Package, err: Error) {
	qb: _Query_Builder
	_qb_init(&qb)
	_qb_maybe_bool(&qb, "roll_up", opts.roll_up)
	path := fmt.tprintf("/users/%v/budget", id)
	resp := _execute(c, "GET", path, _qb_string(&qb), nil, allocator) or_return
	defer delete(resp.body, allocator)
	result = _decode([]Budget_Analysis_Package, resp.body, allocator) or_return
	return
}

// Get budget summary for user
//
// Get the user's budget summary, containing an expense and income analysis for all categories (excluding transfer categories) for the given period and date range. Akin to the overall budget shown on the Budget page in PocketSmith.
get_budget_summary_for_user :: proc(
	c: ^Client,
	id: i64,
	period: string,
	interval: i64,
	start_date: string,
	end_date: string,
	allocator := context.allocator,
) -> (result: []Budget_Analysis_Package, err: Error) {
	qb: _Query_Builder
	_qb_init(&qb)
	_qb_add_string(&qb, "period", period)
	_qb_add_i64(&qb, "interval", interval)
	_qb_add_string(&qb, "start_date", start_date)
	_qb_add_string(&qb, "end_date", end_date)
	path := fmt.tprintf("/users/%v/budget_summary", id)
	resp := _execute(c, "GET", path, _qb_string(&qb), nil, allocator) or_return
	defer delete(resp.body, allocator)
	result = _decode([]Budget_Analysis_Package, resp.body, allocator) or_return
	return
}

// Delete forecast cache for user
//
// Delete the user's cached forecast by recalculating the forecast.
delete_forecast_cache_for_user :: proc(
	c: ^Client,
	id: i64,
	allocator := context.allocator,
) -> (err: Error) {
	path := fmt.tprintf("/users/%v/forecast_cache", id)
	resp := _execute(c, "DELETE", path, "", nil, allocator) or_return
	delete(resp.body, allocator)
	return
}

// Get trend analysis for user
//
// Get an income and/or expense budget analysis for the given date range and period across any number of categories and scenarios. Akin to the Trends page in PocketSmith.
get_trend_analysis_for_user :: proc(
	c: ^Client,
	id: i64,
	period: string,
	interval: i64,
	start_date: string,
	end_date: string,
	categories: string,
	scenarios: string,
	allocator := context.allocator,
) -> (result: []Budget_Analysis_Package, err: Error) {
	qb: _Query_Builder
	_qb_init(&qb)
	_qb_add_string(&qb, "period", period)
	_qb_add_i64(&qb, "interval", interval)
	_qb_add_string(&qb, "start_date", start_date)
	_qb_add_string(&qb, "end_date", end_date)
	_qb_add_string(&qb, "categories", categories)
	_qb_add_string(&qb, "scenarios", scenarios)
	path := fmt.tprintf("/users/%v/trend_analysis", id)
	resp := _execute(c, "GET", path, _qb_string(&qb), nil, allocator) or_return
	defer delete(resp.body, allocator)
	result = _decode([]Budget_Analysis_Package, resp.body, allocator) or_return
	return
}
