// Code generated by odin-api-gen. DO NOT EDIT.
// Source: openapi.json — tag "Time Zones"
package pocketsmith


// List time zones
//
// Lists time zones.
list_time_zones :: proc(
	c: ^Client,
	allocator := context.allocator,
) -> (result: []Time_Zone, err: Error) {
	path := "/time_zones"
	resp := _execute(c, "GET", path, "", nil, allocator) or_return
	defer delete(resp.body, allocator)
	result = _decode([]Time_Zone, resp.body, allocator) or_return
	return
}
