// Code generated by odin-api-gen. DO NOT EDIT.
// Source: openapi.json — tag "Categories"
package pocketsmith

import "core:fmt"

// Get category
//
// Gets a particular category by its ID.
get_category :: proc(
	c: ^Client,
	id: i64,
	allocator := context.allocator,
) -> (result: Category, err: Error) {
	path := fmt.tprintf("/categories/%v", id)
	resp := _execute(c, "GET", path, "", nil, allocator) or_return
	defer delete(resp.body, allocator)
	result = _decode(Category, resp.body, allocator) or_return
	return
}

// Update category
//
// Updates a category by its ID.
update_category :: proc(
	c: ^Client,
	id: i64,
	body: Update_Category_Body,
	allocator := context.allocator,
) -> (result: Category, err: Error) {
	body_data := _encode(body, allocator) or_return
	path := fmt.tprintf("/categories/%v", id)
	resp := _execute(c, "PUT", path, "", body_data, allocator) or_return
	defer delete(resp.body, allocator)
	result = _decode(Category, resp.body, allocator) or_return
	return
}

// Delete category
//
// Deletes a particular category by its ID. This will delete all budgets within the category, and uncategorize all transactions assigned to the category.
delete_category :: proc(
	c: ^Client,
	id: i64,
	allocator := context.allocator,
) -> (err: Error) {
	path := fmt.tprintf("/categories/%v", id)
	resp := _execute(c, "DELETE", path, "", nil, allocator) or_return
	delete(resp.body, allocator)
	return
}

// List categories in user
//
// Lists all categories belonging to a user by their ID.
list_categories_in_user :: proc(
	c: ^Client,
	id: i64,
	allocator := context.allocator,
) -> (result: []Category, err: Error) {
	path := fmt.tprintf("/users/%v/categories", id)
	resp := _execute(c, "GET", path, "", nil, allocator) or_return
	defer delete(resp.body, allocator)
	result = _decode([]Category, resp.body, allocator) or_return
	return
}

// Create category in user
//
// Creates a category belonging to the user by their ID.
create_category_in_user :: proc(
	c: ^Client,
	id: i64,
	body: Create_Category_In_User_Body,
	allocator := context.allocator,
) -> (result: Category, err: Error) {
	body_data := _encode(body, allocator) or_return
	path := fmt.tprintf("/users/%v/categories", id)
	resp := _execute(c, "POST", path, "", body_data, allocator) or_return
	defer delete(resp.body, allocator)
	result = _decode(Category, resp.body, allocator) or_return
	return
}
