// Code generated by odin-api-gen. DO NOT EDIT.
// Source: openapi.json — tag "Users"
package pocketsmith

import "core:fmt"

// Get the authorised user
//
// Gets the user that corresponds to the access token used in the request.
get_authorised_user :: proc(
	c: ^Client,
	allocator := context.allocator,
) -> (result: User, err: Error) {
	path := "/me"
	resp := _execute(c, "GET", path, "", nil, allocator) or_return
	defer delete(resp.body, allocator)
	result = _decode(User, resp.body, allocator) or_return
	return
}

// Get user
//
// Gets a user by ID. You must be authorised as the target user in order to make this request.
get_user :: proc(
	c: ^Client,
	id: i64,
	allocator := context.allocator,
) -> (result: User, err: Error) {
	path := fmt.tprintf("/users/%v", id)
	resp := _execute(c, "GET", path, "", nil, allocator) or_return
	defer delete(resp.body, allocator)
	result = _decode(User, resp.body, allocator) or_return
	return
}

// Update user
//
// Updates the user by their ID. You must be authorised as the target user in order to make this request.
update_user :: proc(
	c: ^Client,
	id: i64,
	body: Update_User_Body,
	allocator := context.allocator,
) -> (result: User, err: Error) {
	body_data := _encode(body, allocator) or_return
	path := fmt.tprintf("/users/%v", id)
	resp := _execute(c, "PUT", path, "", body_data, allocator) or_return
	defer delete(resp.body, allocator)
	result = _decode(User, resp.body, allocator) or_return
	return
}
