// Code generated by odin-api-gen. DO NOT EDIT.
// Source: openapi.json — tag "Accounts"
package pocketsmith

import "core:fmt"

// Get account
//
// Gets an account by its ID.
get_account :: proc(
	c: ^Client,
	id: i64,
	allocator := context.allocator,
) -> (result: Account, err: Error) {
	path := fmt.tprintf("/accounts/%v", id)
	resp := _execute(c, "GET", path, "", nil, allocator) or_return
	defer delete(resp.body, allocator)
	result = _decode(Account, resp.body, allocator) or_return
	return
}

// Update account
//
// Updates and returns an account by its ID.
update_account :: proc(
	c: ^Client,
	id: i64,
	body: Update_Account_Body,
	allocator := context.allocator,
) -> (result: Account, err: Error) {
	body_data := _encode(body, allocator) or_return
	path := fmt.tprintf("/accounts/%v", id)
	resp := _execute(c, "PUT", path, "", body_data, allocator) or_return
	defer delete(resp.body, allocator)
	result = _decode(Account, resp.body, allocator) or_return
	return
}

// Delete account
//
// Deletes an account and all its data by ID, optionally merge scenarios into another account.
delete_account :: proc(
	c: ^Client,
	id: i64,
	allocator := context.allocator,
) -> (err: Error) {
	path := fmt.tprintf("/accounts/%v", id)
	resp := _execute(c, "DELETE", path, "", nil, allocator) or_return
	delete(resp.body, allocator)
	return
}

// List accounts in institution
//
// Lists accounts belonging to an institution by its ID.
list_accounts_in_institution :: proc(
	c: ^Client,
	id: i64,
	allocator := context.allocator,
) -> (result: []Account, err: Error) {
	path := fmt.tprintf("/institutions/%v/accounts", id)
	resp := _execute(c, "GET", path, "", nil, allocator) or_return
	defer delete(resp.body, allocator)
	result = _decode([]Account, resp.body, allocator) or_return
	return
}

// List accounts in user
//
// Lists all accounts belonging to the user by their ID.
list_accounts_in_user :: proc(
	c: ^Client,
	id: i64,
	allocator := context.allocator,
) -> (result: []Account, err: Error) {
	path := fmt.tprintf("/users/%v/accounts", id)
	resp := _execute(c, "GET", path, "", nil, allocator) or_return
	defer delete(resp.body, allocator)
	result = _decode([]Account, resp.body, allocator) or_return
	return
}

// Create an account in user
//
// Creates and returns an account belonging to the user by their ID.
create_account_in_user :: proc(
	c: ^Client,
	id: i64,
	body: Create_Account_In_User_Body,
	allocator := context.allocator,
) -> (result: Account, err: Error) {
	body_data := _encode(body, allocator) or_return
	path := fmt.tprintf("/users/%v/accounts", id)
	resp := _execute(c, "POST", path, "", body_data, allocator) or_return
	defer delete(resp.body, allocator)
	result = _decode(Account, resp.body, allocator) or_return
	return
}

// Update the display order of accounts in user
//
// Updates the display order of accounts belonging to the user, by accepting an array of accounts in their new display order.
update_display_order_of_accounts_in_user :: proc(
	c: ^Client,
	id: i64,
	body: Update_Display_Order_Of_Accounts_In_User_Body,
	allocator := context.allocator,
) -> (result: []Account, err: Error) {
	body_data := _encode(body, allocator) or_return
	path := fmt.tprintf("/users/%v/accounts", id)
	resp := _execute(c, "PUT", path, "", body_data, allocator) or_return
	defer delete(resp.body, allocator)
	result = _decode([]Account, resp.body, allocator) or_return
	return
}
