// Code generated by odin-api-gen. DO NOT EDIT.
// Source: openapi.json — tag "Transactions"
package pocketsmith

import "core:fmt"
import "core:encoding/json"

// Optional query parameters for list_transactions_in_account.
List_Transactions_In_Account_Options :: struct {
	// Limit to transactions on or after this date. Required if end_date is provided. If not provided, defaults to the furtherest date allowed by the user's subscription.
	start_date: Maybe(string),
	// Limit to transactions on or before this date. Required if start_date is provided. If not provided, defaults to today's date.
	end_date: Maybe(string),
	// Limit to transactions updated since an ISO 8601 timestamp.
	updated_since: Maybe(string),
	// Limit to uncategorised transactions.
	uncategorised: Maybe(i64),
	// Limit to transactions of this type.
	// Allowed values: "debit", "credit".
	type: Maybe(string),
	// Limit to transactions that need to be reviewed.
	needs_review: Maybe(i64),
	// Limit to transactions matching a keyword search string. The provided string is matched against the transaction amount, account name, payee, category title, note, labels, and the date in ISO 8601 format.
	search: Maybe(string),
	// Choose a particular page of the results.
	page: Maybe(i64),
}

// Optional query parameters for list_transactions_in_categories.
List_Transactions_In_Categories_Options :: struct {
	// Limit to transactions on or after this date. Required if end_date is provided. If not provided, defaults to the furtherest date allowed by the user's subscription.
	start_date: Maybe(string),
	// Limit to transactions on or before this date. Required if start_date is provided. If not provided, defaults to today's date.
	end_date: Maybe(string),
	// Limit to transactions updated since an ISO 8601 timestamp.
	updated_since: Maybe(string),
	// Limit to uncategorised transactions.
	uncategorised: Maybe(i64),
	// Limit to transactions of this type.
	// Allowed values: "debit", "credit".
	type: Maybe(string),
	// Limit to transactions that need to be reviewed.
	needs_review: Maybe(i64),
	// Limit to transactions matching a keyword search string. The provided string is matched against the transaction amount, account name, payee, category title, note, labels, and the date in ISO 8601 format.
	search: Maybe(string),
	// Choose a particular page of the results.
	page: Maybe(i64),
}

// Optional query parameters for list_transactions_in_transaction_account.
List_Transactions_In_Transaction_Account_Options :: struct {
	// Limit to transactions on or after this date. Required if end_date is provided. If not provided, defaults to the furtherest date allowed by the user's subscription.
	start_date: Maybe(string),
	// Limit to transactions on or before this date. Required if start_date is provided. If not provided, defaults to today's date.
	end_date: Maybe(string),
	// Limit to transactions updated since an ISO 8601 timestamp.
	updated_since: Maybe(string),
	// Limit to uncategorised transactions.
	uncategorised: Maybe(i64),
	// Limit to transactions of this type.
	// Allowed values: "debit", "credit".
	type: Maybe(string),
	// Limit to transactions that need to be reviewed.
	needs_review: Maybe(i64),
	// Limit to transactions matching a keyword search string. The provided string is matched against the transaction amount, account name, payee, category title, note, labels, and the date in ISO 8601 format.
	search: Maybe(string),
	// Choose a particular page of the results.
	page: Maybe(i64),
}

// Optional query parameters for list_transactions_in_user.
List_Transactions_In_User_Options :: struct {
	// Limit to transactions on or after this date. Required if end_date is provided. If not provided, defaults to the furtherest date allowed by the user's subscription.
	start_date: Maybe(string),
	// Limit to transactions on or before this date. Required if start_date is provided. If not provided, defaults to today's date.
	end_date: Maybe(string),
	// Limit to transactions updated since an ISO 8601 timestamp.
	updated_since: Maybe(string),
	// Limit to uncategorised transactions.
	uncategorised: Maybe(i64),
	// Limit to transactions of this type.
	// Allowed values: "debit", "credit".
	type: Maybe(string),
	// Limit to transactions that need to be reviewed.
	needs_review: Maybe(i64),
	// Limit to transactions matching a keyword search string. The provided string is matched against the transaction amount, account name, payee, category title, note, labels, and the date in ISO 8601 format.
	search: Maybe(string),
	// Choose a particular page of the results.
	page: Maybe(i64),
}

// List transactions in account
//
// Lists transactions belonging to an account by its ID.
list_transactions_in_account :: proc(
	c: ^Client,
	id: i64,
	opts := List_Transactions_In_Account_Options{},
	allocator := context.allocator,
) -> (result: []Transaction, err: Error) {
	qb: _Query_Builder
	_qb_init(&qb)
	_qb_maybe_string(&qb, "start_date", opts.start_date)
	_qb_maybe_string(&qb, "end_date", opts.end_date)
	_qb_maybe_string(&qb, "updated_since", opts.updated_since)
	_qb_maybe_i64(&qb, "uncategorised", opts.uncategorised)
	_qb_maybe_string(&qb, "type", opts.type)
	_qb_maybe_i64(&qb, "needs_review", opts.needs_review)
	_qb_maybe_string(&qb, "search", opts.search)
	_qb_maybe_i64(&qb, "page", opts.page)
	path := fmt.tprintf("/accounts/%v/transactions", id)
	resp := _execute(c, "GET", path, _qb_string(&qb), nil, allocator) or_return
	defer delete(resp.body, allocator)
	result = _decode([]Transaction, resp.body, allocator) or_return
	return
}

// List transactions in categories
//
// Lists transactions belonging to one or more categories by their IDs.
list_transactions_in_categories :: proc(
	c: ^Client,
	id: string,
	opts := List_Transactions_In_Categories_Options{},
	allocator := context.allocator,
) -> (result: []Transaction, err: Error) {
	qb: _Query_Builder
	_qb_init(&qb)
	_qb_maybe_string(&qb, "start_date", opts.start_date)
	_qb_maybe_string(&qb, "end_date", opts.end_date)
	_qb_maybe_string(&qb, "updated_since", opts.updated_since)
	_qb_maybe_i64(&qb, "uncategorised", opts.uncategorised)
	_qb_maybe_string(&qb, "type", opts.type)
	_qb_maybe_i64(&qb, "needs_review", opts.needs_review)
	_qb_maybe_string(&qb, "search", opts.search)
	_qb_maybe_i64(&qb, "page", opts.page)
	path := fmt.tprintf("/categories/%v/transactions", id)
	resp := _execute(c, "GET", path, _qb_string(&qb), nil, allocator) or_return
	defer delete(resp.body, allocator)
	result = _decode([]Transaction, resp.body, allocator) or_return
	return
}

// List transactions in transaction account
//
// Lists transactions belonging to a transaction account by its ID.
list_transactions_in_transaction_account :: proc(
	c: ^Client,
	id: i64,
	opts := List_Transactions_In_Transaction_Account_Options{},
	allocator := context.allocator,
) -> (result: []Transaction, err: Error) {
	qb: _Query_Builder
	_qb_init(&qb)
	_qb_maybe_string(&qb, "start_date", opts.start_date)
	_qb_maybe_string(&qb, "end_date", opts.end_date)
	_qb_maybe_string(&qb, "updated_since", opts.updated_since)
	_qb_maybe_i64(&qb, "uncategorised", opts.uncategorised)
	_qb_maybe_string(&qb, "type", opts.type)
	_qb_maybe_i64(&qb, "needs_review", opts.needs_review)
	_qb_maybe_string(&qb, "search", opts.search)
	_qb_maybe_i64(&qb, "page", opts.page)
	path := fmt.tprintf("/transaction_accounts/%v/transactions", id)
	resp := _execute(c, "GET", path, _qb_string(&qb), nil, allocator) or_return
	defer delete(resp.body, allocator)
	result = _decode([]Transaction, resp.body, allocator) or_return
	return
}

// Create a transaction in transaction account
//
// Creates a transaction in a transaction account by its ID.
create_transaction_in_transaction_account :: proc(
	c: ^Client,
	id: i64,
	body: Create_Transaction_In_Transaction_Account_Body,
	allocator := context.allocator,
) -> (result: Transaction, err: Error) {
	body_data := _encode(body, allocator) or_return
	path := fmt.tprintf("/transaction_accounts/%v/transactions", id)
	resp := _execute(c, "POST", path, "", body_data, allocator) or_return
	defer delete(resp.body, allocator)
	result = _decode(Transaction, resp.body, allocator) or_return
	return
}

// Get a transaction
//
// Gets a transaction by its ID.
get_transaction :: proc(
	c: ^Client,
	id: i64,
	allocator := context.allocator,
) -> (result: Transaction, err: Error) {
	path := fmt.tprintf("/transactions/%v", id)
	resp := _execute(c, "GET", path, "", nil, allocator) or_return
	defer delete(resp.body, allocator)
	result = _decode(Transaction, resp.body, allocator) or_return
	return
}

// Update a transaction
//
// Updates a transaction by its ID.
update_transaction :: proc(
	c: ^Client,
	id: i64,
	body: Update_Transaction_Body,
	allocator := context.allocator,
) -> (result: json.Value, err: Error) {
	body_data := _encode(body, allocator) or_return
	path := fmt.tprintf("/transactions/%v", id)
	resp := _execute(c, "PUT", path, "", body_data, allocator) or_return
	defer delete(resp.body, allocator)
	result = _decode_value(resp.body, allocator) or_return
	return
}

// Delete transaction
//
// Deletes a transaction and all its data by ID.
delete_transaction :: proc(
	c: ^Client,
	id: i64,
	allocator := context.allocator,
) -> (err: Error) {
	path := fmt.tprintf("/transactions/%v", id)
	resp := _execute(c, "DELETE", path, "", nil, allocator) or_return
	delete(resp.body, allocator)
	return
}

// List transactions in user
//
// Lists transactions belonging to a user by their ID.
list_transactions_in_user :: proc(
	c: ^Client,
	id: i64,
	opts := List_Transactions_In_User_Options{},
	allocator := context.allocator,
) -> (result: []Transaction, err: Error) {
	qb: _Query_Builder
	_qb_init(&qb)
	_qb_maybe_string(&qb, "start_date", opts.start_date)
	_qb_maybe_string(&qb, "end_date", opts.end_date)
	_qb_maybe_string(&qb, "updated_since", opts.updated_since)
	_qb_maybe_i64(&qb, "uncategorised", opts.uncategorised)
	_qb_maybe_string(&qb, "type", opts.type)
	_qb_maybe_i64(&qb, "needs_review", opts.needs_review)
	_qb_maybe_string(&qb, "search", opts.search)
	_qb_maybe_i64(&qb, "page", opts.page)
	path := fmt.tprintf("/users/%v/transactions", id)
	resp := _execute(c, "GET", path, _qb_string(&qb), nil, allocator) or_return
	defer delete(resp.body, allocator)
	result = _decode([]Transaction, resp.body, allocator) or_return
	return
}
