// Code generated by odin-api-gen. DO NOT EDIT.
// Source: openapi.json — tag "Category Rules"
package pocketsmith

import "core:fmt"

// Create category rule in category
//
// Creates a rule to allocate a category to transactions.
create_category_rule_in_category :: proc(
	c: ^Client,
	id: i64,
	body: Create_Category_Rule_In_Category_Body,
	allocator := context.allocator,
) -> (result: Category_Rule, err: Error) {
	body_data := _encode(body, allocator) or_return
	path := fmt.tprintf("/categories/%v/category_rules", id)
	resp := _execute(c, "POST", path, "", body_data, allocator) or_return
	defer delete(resp.body, allocator)
	result = _decode(Category_Rule, resp.body, allocator) or_return
	return
}

// List category rules in user
//
// Lists all category rules belonging to a user by their ID.
list_category_rules_in_user :: proc(
	c: ^Client,
	id: i64,
	allocator := context.allocator,
) -> (result: []Category_Rule, err: Error) {
	path := fmt.tprintf("/users/%v/category_rules", id)
	resp := _execute(c, "GET", path, "", nil, allocator) or_return
	defer delete(resp.body, allocator)
	result = _decode([]Category_Rule, resp.body, allocator) or_return
	return
}
