// Code generated by odin-api-gen. DO NOT EDIT.
// Source: openapi.json — tag "Currencies"
package pocketsmith

import "core:fmt"

// List currencies
//
// Lists currencies supported by PocketSmith.
list_currencies :: proc(
	c: ^Client,
	allocator := context.allocator,
) -> (result: []Currency, err: Error) {
	path := "/currencies"
	resp := _execute(c, "GET", path, "", nil, allocator) or_return
	defer delete(resp.body, allocator)
	result = _decode([]Currency, resp.body, allocator) or_return
	return
}

// Get currency
//
// Gets a particular currency by its ID.
get_currency :: proc(
	c: ^Client,
	id: string,
	allocator := context.allocator,
) -> (result: Currency, err: Error) {
	path := fmt.tprintf("/currencies/%v", id)
	resp := _execute(c, "GET", path, "", nil, allocator) or_return
	defer delete(resp.body, allocator)
	result = _decode(Currency, resp.body, allocator) or_return
	return
}
