// Code generated by odin-api-gen. DO NOT EDIT.
// Source: openapi.json — tag "Labels"
package pocketsmith

import "core:fmt"

// List labels in user
//
// Lists labels belonging to a user by their ID.
list_labels_in_user :: proc(
	c: ^Client,
	id: i64,
	allocator := context.allocator,
) -> (result: []string, err: Error) {
	path := fmt.tprintf("/users/%v/labels", id)
	resp := _execute(c, "GET", path, "", nil, allocator) or_return
	defer delete(resp.body, allocator)
	result = _decode([]string, resp.body, allocator) or_return
	return
}
