// Code generated by odin-api-gen. DO NOT EDIT.
// Source: openapi.json — tag "Transaction Accounts"
package pocketsmith

import "core:fmt"

// Get transaction account
//
// Gets a transaction account by its ID.
get_transaction_account :: proc(
	c: ^Client,
	id: i64,
	allocator := context.allocator,
) -> (result: Transaction_Account, err: Error) {
	path := fmt.tprintf("/transaction_accounts/%v", id)
	resp := _execute(c, "GET", path, "", nil, allocator) or_return
	defer delete(resp.body, allocator)
	result = _decode(Transaction_Account, resp.body, allocator) or_return
	return
}

// Update transaction account
//
// Updates the transaction account by its ID.
update_transaction_account :: proc(
	c: ^Client,
	id: i64,
	body: Update_Transaction_Account_Body,
	allocator := context.allocator,
) -> (result: Transaction_Account, err: Error) {
	body_data := _encode(body, allocator) or_return
	path := fmt.tprintf("/transaction_accounts/%v", id)
	resp := _execute(c, "PUT", path, "", body_data, allocator) or_return
	defer delete(resp.body, allocator)
	result = _decode(Transaction_Account, resp.body, allocator) or_return
	return
}

// List transaction accounts in user
//
// List all transaction accounts belonging to a user.
list_transaction_accounts_in_user :: proc(
	c: ^Client,
	id: i64,
	allocator := context.allocator,
) -> (result: []Transaction_Account, err: Error) {
	path := fmt.tprintf("/users/%v/transaction_accounts", id)
	resp := _execute(c, "GET", path, "", nil, allocator) or_return
	defer delete(resp.body, allocator)
	result = _decode([]Transaction_Account, resp.body, allocator) or_return
	return
}
