// Code generated by odin-api-gen. DO NOT EDIT.
// Source: openapi.json
package pocketsmith

Account :: struct {
	// When the account was created.
	created_at: string,
	// The currency code for the account.
	currency_code: string,
	// The current balance of the account.
	current_balance: f64,
	// The date of the current balance.
	current_balance_date: string,
	// The exchange rate between the account's currency and the user's base currency, when different. If the currencies are the same, null is returned.
	current_balance_exchange_rate: f64,
	// The current balance of the account in the user's base currency.
	current_balance_in_base_currency: f64,
	// The unique identifier of the account.
	id: i64,
	// Whether the account is a net worth asset.
	is_net_worth: bool,
	primary_scenario: Scenario,
	primary_transaction_account: Transaction_Account,
	// The current safe balance, if safe balance is activated on the account. If safe balance is not activated, then null is returned.
	safe_balance: f64,
	// The current safe balance in the user's base currency, if safe balance is activated on the account. If safe balance is not activated, then null is returned.
	safe_balance_in_base_currency: f64,
	// All scenarios that compose the account, including the primary.
	scenarios: []Scenario,
	// The title of the account.
	title: string,
	// All transaction accounts that compose the account, including the primary.
	transaction_accounts: []Transaction_Account,
	// The type of the account.
	type: string,
	// When the account was last updated.
	updated_at: string,
}

// Request body for assign_attachment_to_transaction.
Assign_Attachment_To_Transaction_Body :: struct {
	// The unique identifier of the attachment.
	attachment_id: Maybe(i64) `json:"attachment_id,omitempty"`,
}

Attachment :: struct {
	// The content type of the attachment.
	content_type: string,
	content_type_meta: Attachment_Content_Type_Meta,
	// When the attachment was created.
	created_at: string,
	// The file name of the attachment.
	file_name: string,
	// The unique identifier of the attachment
	id: i64,
	// The url of the attachment.
	original_url: string,
	// The title of the attachment. If blank or not provided, the title will be derived from the file name.
	title: string,
	// The type of attachment.
	type: string,
	// When the attachment was last updated.
	updated_at: string,
	variants: Attachment_Variants,
}

Attachment_Content_Type_Meta :: struct {
	// The content type description of the attachment.
	description: string,
	// The extension type of the attachment.
	extension: string,
	// The content type title of the attachment.
	title: string,
}

Attachment_Variants :: struct {
	// The url of the large version of the attachment.
	large_url: string,
	// The url of the thumb version of the attachment.
	thumb_url: string,
}

Budget_Analysis :: struct {
	// The average actual (transactions) amount across all periods.
	average_actual_amount: f64,
	// The average budgeted amount across all periods.
	average_forecast_amount: f64,
	// The currency of the budget analysis.
	currency_code: string,
	// The end date of the budget analysis.
	end_date: string,
	// The period analyses that this budget analysis comprises.
	periods: []Period,
	// The start date of the budget analysis.
	start_date: string,
	// The total actual (transactions) amount across all periods.
	total_actual_amount: f64,
	// The total budgeted amount across all periods.
	total_forecast_amount: f64,
	// The total amount the budget was exceeded across all periods.
	total_over_by: f64,
	// The total amount the budget was under by across all periods.
	total_under_by: f64,
}

Budget_Analysis_Package :: struct {
	category: Category,
	expense: Budget_Analysis,
	income: Budget_Analysis,
	// Whether the expense budget analysis looks like a transfer to the income budget analysis, based on a number of heuristics.
	is_transfer: bool,
}

Category :: struct {
	// The category's child categories.
	children: []Category,
	// The colour for the category.
	colour: string,
	// When the category was created.
	created_at: string,
	// The unique identifier of the category.
	id: i64,
	// Whether the category is a bill category. A bill category is when budgeted amounts are normally spent at once, instead of spread across a budgeting period. This category will be included in the bill reminder email when set to true.
	is_bill: bool,
	// Whether this category has been marked as a transfer category.
	is_transfer: bool,
	// The unique identifier of the parent category of this category, or null if this category has no parent (i.e. is a top-level category)
	parent_id: i64,
	// How the category's refunds or deductions should be reported on.
	refund_behaviour: Maybe(string),
	// Whether the category's budget is rolled up into its parent category, if a parent category is present.
	roll_up: bool,
	// The title of the category.
	title: string,
	// When the category was last updated.
	updated_at: string,
}

Category_Rule :: struct {
	category: Category,
	// When the category rule was created.
	created_at: string,
	// The unique identifier of the category rule.
	id: i64,
	// The keyword/s to match the transactions payees.
	payee_matches: string,
	// When the category rule was last updated.
	updated_at: string,
}

// Request body for create_account_in_user.
Create_Account_In_User_Body :: struct {
	// A currency code for the account.
	currency_code: string,
	// The ID of the institution to create this account in.
	institution_id: i64,
	// A title for the account.
	title: string,
	// The type of the account.
	type: string,
}

// Request body for create_attachment_in_user.
Create_Attachment_In_User_Body :: struct {
	// The base64-encoded contents of the source file. The supported file types are png, jpg, pdf, xls, xlsx, doc, docx.
	file_data: Maybe(string) `json:"file_data,omitempty"`,
	// The file name of the attachment.
	file_name: Maybe(string) `json:"file_name,omitempty"`,
	// The title of the attachment. If the title is blank or not provided, the title will derived from the file name.
	title: Maybe(string) `json:"title,omitempty"`,
}

// Request body for create_category_in_user.
Create_Category_In_User_Body :: struct {
	// A CSS-style hex colour for the category.
	colour: Maybe(string) `json:"colour,omitempty"`,
	// Set the category as a bill category.
	is_bill: Maybe(bool) `json:"is_bill,omitempty"`,
	// Set the category as a transfer category.
	is_transfer: Maybe(bool) `json:"is_transfer,omitempty"`,
	// The unique identifier of a category to be the parent of this category.
	parent_id: Maybe(i64) `json:"parent_id,omitempty"`,
	// Set the refund behaviour of the category.
	refund_behaviour: Maybe(string) `json:"refund_behaviour,omitempty"`,
	// Set the category to be rolled up into its parent category.
	roll_up: Maybe(bool) `json:"roll_up,omitempty"`,
	// A title for the category.
	title: string,
}

// Request body for create_category_rule_in_category.
Create_Category_Rule_In_Category_Body :: struct {
	// Apply the created category rule to all transactions.
	apply_to_all: Maybe(bool) `json:"apply_to_all,omitempty"`,
	// Apply the created category rule to all uncategorised transactions.
	apply_to_uncategorised: Maybe(bool) `json:"apply_to_uncategorised,omitempty"`,
	// The keyword/s to match the transaction payees.
	payee_matches: string,
}

// Request body for create_event_in_scenario.
Create_Event_In_Scenario_Body :: struct {
	// The amount of the event. A positive amount is a credit, and a negative amount is a debit.
	amount: f64,
	// The unique identifier of the category for the event.
	category_id: i64,
	// The starting date of the event.
	date: string,
	// A note for the event.
	note: Maybe(string) `json:"note,omitempty"`,
	// The repeat interval of the event.
	repeat_interval: Maybe(i64) `json:"repeat_interval,omitempty"`,
	// The repeat type of the event.
	repeat_type: string,
}

// Request body for create_institution_in_user.
Create_Institution_In_User_Body :: struct {
	// A currency code for the institution.
	currency_code: string,
	// A title for the institution.
	title: string,
}

// Request body for create_transaction_in_transaction_account.
Create_Transaction_In_Transaction_Account_Body :: struct {
	// The amount of the transaction (signed). A positive amount is a credit, and a negative amount is a debit.
	amount: f64,
	// The unique identifier of a category for the transaction.
	category_id: Maybe(i64) `json:"category_id,omitempty"`,
	// A cheque number for the transaction.
	cheque_number: Maybe(string) `json:"cheque_number,omitempty"`,
	// The date when the transaction occurred.
	date: string,
	// Whether the transaction should be indicated as a transfer.
	is_transfer: Maybe(bool) `json:"is_transfer,omitempty"`,
	// A set of comma-separated labels for the transaction.
	labels: Maybe(string) `json:"labels,omitempty"`,
	// A memo for the transaction.
	memo: Maybe(string) `json:"memo,omitempty"`,
	// Whether the transaction needs to be reviewed or not.
	needs_review: Maybe(bool) `json:"needs_review,omitempty"`,
	// A note for the transaction.
	note: Maybe(string) `json:"note,omitempty"`,
	// The payee/merchant of the transaction.
	payee: string,
}

Currency :: struct {
	// The ISO 4217 or unofficial currency code.
	id: string,
	// The number of digits after the minor unit separator.
	minor_unit: i64,
	// The name of the currency.
	name: string,
	separators: Currency_Separators,
	// The symbol of the currency.
	symbol: string,
}

Currency_Separators :: struct {
	// The separator used in the major unit.
	major: string,
	// The seperator used for the minor unit.
	minor: string,
}

Event :: struct {
	// The amount of the event.
	amount: f64,
	// The amount of the event in the user's base currency.
	amount_in_base_currency: f64,
	category: Category,
	// The CSS hex-style colour of the event.
	colour: string,
	// The currency code of the event.
	currency_code: string,
	// The date of the event.
	date: string,
	// The unique identifier of the event.
	id: string,
	// Whether the event repeats and does not have an end date.
	infinite_series: bool,
	// The note of the event.
	note: string,
	// The repeat interval of how often the event takes place.
	repeat_interval: i64,
	// The repeat type of the event.
	repeat_type: string,
	scenario: Scenario,
	// The unique identifier of the series that the event belongs to.
	series_id: i64,
	// The unique identifier of the series followed by the series's start date.
	series_start_id: string,
}

Institution :: struct {
	// When the institution was created.
	created_at: string,
	// The currency code of the institution.
	currency_code: string,
	// The unique identifier of the institution.
	id: i64,
	// The title of the institution.
	title: string,
	// When the institution was last updated.
	updated_at: string,
}

Period :: struct {
	// The sum of all actuals (transactions) in the period.
	actual_amount: f64,
	// The currency of the period.
	currency_code: string,
	// Whether this period is current, such that the current date (in the user's time zone) falls within the date range.
	current: bool,
	// The end date of the period.
	end_date: string,
	// The sum of all forecast sources (budget events) in the period, for comparison against the actual amount.
	forecast_amount: f64,
	// Whether the budget has been exceeded in the period.
	over_budget: bool,
	// How much the budget has been exceeded by in the period.
	over_by: f64,
	// The percentage of the budget that has been used in the period.
	percentage_used: f64,
	// This attribute tracks the amount that has been refunded or deducted to the actual amount. When a category is set to "always expense", any credit transactions are treated as refunds and when set to "always income", any debit transactions are treated as deductions.
	refund_amount: f64,
	// The start date of the period.
	start_date: string,
	// Whether the budget has not been exceeded in the period.
	under_budget: bool,
	// How much there is left in the budget for the period.
	under_by: f64,
}

Saved_Search :: struct {
	// When the saved search was created.
	created_at: string,
	// The unique identifier of the saved search.
	id: i64,
	// The title of the saved search.
	title: string,
	// When the saved search was last updated.
	updated_at: string,
}

Scenario :: struct {
	// For goals, the date that they should be achieved by.
	achieve_date: string,
	// The closing balance of the scenario.
	closing_balance: f64,
	// The date of the closing balance.
	closing_balance_date: string,
	// When the scenario was created.
	created_at: string,
	// The current balance of the scenario.
	current_balance: f64,
	// The date of the current balance.
	current_balance_date: string,
	// The exchange rate between the scenario's currency and the user's base currency, when different. If the currencies are the same, null is returned.
	current_balance_exchange_rate: f64,
	// The current balance of the scenario in the user's base currency.
	current_balance_in_base_currency: f64,
	// A short description of what the scenario is modelling.
	description: string,
	// The unique identifier of the scenario.
	id: i64,
	// The amount of interest to apply to the balance. Will apply periodically depending on what `interest_rate_repeat_id` is set to.
	interest_rate: f64,
	// A number representing how often the interest should be applied. 0 is used for no interest, 2 is weekly, 3 is fortnightly, 4 is monthly, 5 is yearly and 7 for quarterly.
	interest_rate_repeat_id: i64,
	maximum_value: f64 `json:"maximum-value"`,
	minimum_value: f64 `json:"minimum-value"`,
	// The current safe balance in the user's base currency, if safe balance is activated on the account associated with the scenario. If safe balance is not activated, then null is returned.
	safe_balance: f64,
	// The current safe balance in the user's base currency, if safe balance is activated on the account associated with the scenario. If safe balance is not available, then null is returned.
	safe_balance_in_base_currency: f64,
	// The starting balance of the scenario.
	starting_balance: f64,
	// The date of the starting balance.
	starting_balance_date: string,
	// The title of the scenario.
	title: string,
	// The type of the scenario.
	type: string,
	// When the scenario was last updated.
	updated_at: string,
}

Time_Zone :: struct {
	// The abbreviation of the time zone.
	abbreviation: string,
	// The formatted name of the time zone.
	formatted_name: string,
	// The formatted offset of the time zone.
	formatted_offset: string,
	// The tz database name of the time zone.
	identifier: string,
	// The name of the time zone.
	name: string,
	// The time zone's UTC offset in seconds.
	utc_offset: i64,
}

Transaction :: struct {
	amount: f64,
	// The amount of the transaction in the user's base currency.
	amount_in_base_currency: f64,
	category: Category,
	cheque_number: string,
	// The closing balance of the account at the transaction.
	closing_balance: f64,
	// When the transaction was created.
	created_at: string,
	// The date the transaction took place.
	date: string,
	// The unique identifier of the transaction.
	id: i64,
	// Whether the transaction is a transfer.
	is_transfer: bool,
	labels: []string,
	memo: string,
	// Whether the transaction needs to be reviewed.
	needs_review: bool,
	note: string,
	// The payee the transaction was created with.
	original_payee: string,
	// The payee/merchant of the transaction.
	payee: string,
	// The status of the transaction. Pending transactions are temporary and may be superseded later by their posted counterparts, which are permanent.
	status: string,
	transaction_account: Transaction_Account,
	// Whether the transaction is a debit or a credit
	type: string,
	// When the transaction was last updated.
	updated_at: string,
	// Where the transaction came from.
	upload_source: string,
}

Transaction_Account :: struct {
	created_at: string,
	// The currency that the account is in. This is determined by the account that the transaction account belongs to.
	currency_code: string,
	current_balance: f64,
	current_balance_date: string,
	// The exchange rate between the transaction account's currency and the user's base currency, when different. If the currencies are the same, null is returned.
	current_balance_exchange_rate: f64,
	// The current balance of the transaction account in the user's base currency.
	current_balance_in_base_currency: f64,
	id: i64,
	institution: Institution,
	name: string,
	number: string,
	// The current safe balance, if safe balance is activated and available for the transaction account. If safe balance is not available, then null is returned.
	safe_balance: f64,
	// The current safe balance in the user's base currency, if safe balance is activated and available for the transaction account. If safe balance is not available, then null is returned.
	safe_balance_in_base_currency: f64,
	starting_balance: f64,
	starting_balance_date: string,
	// The type of the transaction account.
	type: string,
	updated_at: string,
}

// Request body for update_account.
Update_Account_Body :: struct {
	// A new currency code for the account.
	currency_code: Maybe(string) `json:"currency_code,omitempty"`,
	// Whether the account is a net worth account.
	is_net_worth: Maybe(bool) `json:"is_net_worth,omitempty"`,
	// A new title for the account.
	title: Maybe(string) `json:"title,omitempty"`,
	// The type of the account.
	type: Maybe(string) `json:"type,omitempty"`,
}

// Request body for update_attachment.
Update_Attachment_Body :: struct {
	// The new title of the attachment. If the title is blank or not provided, the server will derive a title from the file name.
	title: Maybe(string) `json:"title,omitempty"`,
}

// Request body for update_category.
Update_Category_Body :: struct {
	// A new CSS-style hex colour for the category.
	colour: Maybe(string) `json:"colour,omitempty"`,
	// Set the category as a bill category.
	is_bill: Maybe(bool) `json:"is_bill,omitempty"`,
	// Set the category as a transfer category.
	is_transfer: Maybe(bool) `json:"is_transfer,omitempty"`,
	// The unique identifier of a parent category for the category, making this category a child of that category.
	parent_id: Maybe(i64) `json:"parent_id,omitempty"`,
	// Set the refund behaviour of the category.
	refund_behaviour: Maybe(string) `json:"refund_behaviour,omitempty"`,
	// Set the category to be rolled up into its parent category.
	roll_up: Maybe(bool) `json:"roll_up,omitempty"`,
	// A new title for the category.
	title: Maybe(string) `json:"title,omitempty"`,
}

// Request body for update_display_order_of_accounts_in_user.
Update_Display_Order_Of_Accounts_In_User_Body :: struct {
	// List the account objects in their new display order.
	accounts: []Account,
}

// Request body for update_event.
Update_Event_Body :: struct {
	// The amount of the event. A positive amount is a credit, and a negative amount is a debit.
	amount: Maybe(f64) `json:"amount,omitempty"`,
	// Whether the update applies only to this event, to all events within the series from this event or to all events within the series.
	behaviour: string,
	// A note for the event.
	note: Maybe(string) `json:"note,omitempty"`,
	// The repeat interval of the event.
	repeat_interval: Maybe(i64) `json:"repeat_interval,omitempty"`,
	// The repeat type of the event.
	repeat_type: Maybe(string) `json:"repeat_type,omitempty"`,
}

// Request body for update_institution.
Update_Institution_Body :: struct {
	// A new currency code for the institution.
	currency_code: Maybe(string) `json:"currency_code,omitempty"`,
	// A new title for the institution.
	title: Maybe(string) `json:"title,omitempty"`,
}

// Request body for update_transaction_account.
Update_Transaction_Account_Body :: struct {
	// The unique identifier of a new institution for the transaction account.
	institution_id: Maybe(i64) `json:"institution_id,omitempty"`,
	// The starting balance amount of the transaction account.
	starting_balance: Maybe(f64) `json:"starting_balance,omitempty"`,
	// The starting balance date of the transaction account.
	starting_balance_date: Maybe(string) `json:"starting_balance_date,omitempty"`,
}

// Request body for update_transaction.
Update_Transaction_Body :: struct {
	// The amount of the transaction (signed). A positive amount is a credit, and a negative amount is a debit.
	amount: Maybe(f64) `json:"amount,omitempty"`,
	// The unique identifier of a new category for the transaction. Sending an empty string will uncategorize the transaction.
	category_id: Maybe(i64) `json:"category_id,omitempty"`,
	// A new cheque number for the transaction.
	cheque_number: Maybe(string) `json:"cheque_number,omitempty"`,
	// A new date for the transaction.
	date: Maybe(string) `json:"date,omitempty"`,
	// Whether the transaction is a transfer or not.
	is_transfer: Maybe(bool) `json:"is_transfer,omitempty"`,
	// A new comma-separated set of labels for the transaction.
	labels: Maybe(string) `json:"labels,omitempty"`,
	// A new memo for the transaction.
	memo: Maybe(string) `json:"memo,omitempty"`,
	// Whether the transaction needs to be reviewed or not.
	needs_review: Maybe(bool) `json:"needs_review,omitempty"`,
	// A new note for the transaction.
	note: Maybe(string) `json:"note,omitempty"`,
	// A new payee for the transaction.
	payee: Maybe(string) `json:"payee,omitempty"`,
	// Split this transaction into multiple transactions. The correctly calculated remainder amount parameter must be provided, which is equal to the amount - sum(split_amounts). Splitting is atomic: all splits are validated before the original transaction and any splits are saved.
	splits: Maybe([]Update_Transaction_Body_Splits_Item) `json:"splits,omitempty"`,
}

Update_Transaction_Body_Splits_Item :: struct {
	// The amount for this split transaction.
	amount: f64,
	// The category ID for this split transaction. If not provided, inherits from the parent transaction.
	category_id: Maybe(i64) `json:"category_id,omitempty"`,
	// The date for this split transaction. If not provided, defaults to the parent transaction's date.
	date: Maybe(string) `json:"date,omitempty"`,
	// Whether this split transaction should be indicated as a transfer.
	is_transfer: Maybe(bool) `json:"is_transfer,omitempty"`,
	// The payee for this split transaction. If not provided, inherits from the parent transaction.
	payee: Maybe(string) `json:"payee,omitempty"`,
}

// Request body for update_user.
Update_User_Body :: struct {
	// Whether the user wishes to have all monetary values converted to their base currency.
	always_show_base_currency: Maybe(bool) `json:"always_show_base_currency,omitempty"`,
	// A new base currency code for the user.
	base_currency_code: Maybe(string) `json:"base_currency_code,omitempty"`,
	// Whether the user is a beta user, and wishes to try out new features.
	beta_user: Maybe(bool) `json:"beta_user,omitempty"`,
	// A new name for the user.
	name: Maybe(string) `json:"name,omitempty"`,
	// A new time zone for the user.
	time_zone: Maybe(string) `json:"time_zone,omitempty"`,
	// The day of the week the user wishes their calendars to start on. A number between 0 and 6, where 0 is Sunday and 6 is Saturday.
	week_start_day: Maybe(i64) `json:"week_start_day,omitempty"`,
}

User :: struct {
	// Whether the user wants to see all accounts in their base currency instead of the native account currency.
	always_show_base_currency: bool,
	// The user's total number of available accounts.
	available_accounts: i64,
	// The user's total number of available budgets.
	available_budgets: i64,
	// The URL to the user's avatar.
	avatar_url: string,
	// The user's base currency.
	base_currency_code: string,
	// Whether the user has opted in to beta features.
	beta_user: bool,
	// When the user signed up.
	created_at: string,
	// The user's email address.
	email: string,
	// Whether the user's forecast recalculation should be deferred.
	forecast_defer_recalculate: bool,
	// The date that the user's forecast ends.
	forecast_end_date: string,
	// When the user's forecast was last accessed.
	forecast_last_accessed_at: string,
	// When the user's forecast was last updated.
	forecast_last_updated_at: string,
	// Whether the user's forecast needs to be recalculated.
	forecast_needs_recalculate: bool,
	// The date that the user's forecast starts.
	forecast_start_date: string,
	// The unique identifier of the user.
	id: i64,
	// Whether the user wants to review new transactions, transfer transactions or categorisation.
	is_reviewing_transactions: bool,
	// When the user last interacted with PocketSmith, via any application or the API.
	last_activity_at: string,
	// When the user last logged into PocketSmith.
	last_logged_in_at: string,
	// The user's username.
	login: string,
	// The full name of the user, although not all users will have a name set.
	name: string,
	// The user's time zone.
	time_zone: string,
	// When the user was last updated.
	updated_at: string,
	// Whether the user has multiple currencies in use across their account.
	using_multiple_currencies: bool,
	// The day of the week the user wishes their calendars to start on. A number between 0 and 6, where 0 is Sunday and 6 is Saturday.
	week_start_day: i64,
}

// Allowed values for Scenario.type.
Scenario_Type_No_Interest :: "no-interest"
Scenario_Type_Savings :: "savings"
Scenario_Type_Debt :: "debt"

// Allowed values for Transaction_Account.type.
Transaction_Account_Type_Bank :: "bank"
Transaction_Account_Type_Credits :: "credits"
Transaction_Account_Type_Cash :: "cash"
Transaction_Account_Type_Stocks :: "stocks"
Transaction_Account_Type_Mortgage :: "mortgage"
Transaction_Account_Type_Loans :: "loans"
Transaction_Account_Type_Vehicle :: "vehicle"
Transaction_Account_Type_Property :: "property"
Transaction_Account_Type_Insurance :: "insurance"
Transaction_Account_Type_Other_Asset :: "other_asset"
Transaction_Account_Type_Other_Liability :: "other_liability"

// Allowed values for Account.type.
Account_Type_Bank :: "bank"
Account_Type_Credits :: "credits"
Account_Type_Cash :: "cash"
Account_Type_Stocks :: "stocks"
Account_Type_Mortgage :: "mortgage"
Account_Type_Loans :: "loans"
Account_Type_Vehicle :: "vehicle"
Account_Type_Property :: "property"
Account_Type_Insurance :: "insurance"
Account_Type_Other_Asset :: "other_asset"
Account_Type_Other_Liability :: "other_liability"

// Allowed values for Update_Account_Body.type.
Update_Account_Body_Type_Bank :: "bank"
Update_Account_Body_Type_Credits :: "credits"
Update_Account_Body_Type_Cash :: "cash"
Update_Account_Body_Type_Loans :: "loans"
Update_Account_Body_Type_Mortgage :: "mortgage"
Update_Account_Body_Type_Stocks :: "stocks"
Update_Account_Body_Type_Vehicle :: "vehicle"
Update_Account_Body_Type_Property :: "property"
Update_Account_Body_Type_Insurance :: "insurance"
Update_Account_Body_Type_Other_Asset :: "other_asset"
Update_Account_Body_Type_Other_Liability :: "other_liability"

// Allowed values for Category.refund_behaviour.
Category_Refund_Behaviour_Debits_Are_Deductions :: "debits_are_deductions"
Category_Refund_Behaviour_Credits_Are_Refunds :: "credits_are_refunds"

// Allowed values for Transaction.status.
Transaction_Status_Pending :: "pending"
Transaction_Status_Posted :: "posted"

// Allowed values for Transaction.type.
Transaction_Type_Debit :: "debit"
Transaction_Type_Credit :: "credit"

// Allowed values for Update_Category_Body.refund_behaviour.
Update_Category_Body_Refund_Behaviour_Debits_Are_Deductions :: "debits_are_deductions"
Update_Category_Body_Refund_Behaviour_Credits_Are_Refunds :: "credits_are_refunds"

// Allowed values for Event.repeat_type.
Event_Repeat_Type_Once :: "once"
Event_Repeat_Type_Daily :: "daily"
Event_Repeat_Type_Weekly :: "weekly"
Event_Repeat_Type_Fortnightly :: "fortnightly"
Event_Repeat_Type_Monthly :: "monthly"
Event_Repeat_Type_Yearly :: "yearly"
Event_Repeat_Type_Each_Weekday :: "each weekday"

// Allowed values for Update_Event_Body.behaviour.
Update_Event_Body_Behaviour_One :: "one"
Update_Event_Body_Behaviour_Forward :: "forward"
Update_Event_Body_Behaviour_All :: "all"

// Allowed values for Update_Event_Body.repeat_type.
Update_Event_Body_Repeat_Type_Once :: "once"
Update_Event_Body_Repeat_Type_Daily :: "daily"
Update_Event_Body_Repeat_Type_Weekly :: "weekly"
Update_Event_Body_Repeat_Type_Fortnightly :: "fortnightly"
Update_Event_Body_Repeat_Type_Monthly :: "monthly"
Update_Event_Body_Repeat_Type_Yearly :: "yearly"
Update_Event_Body_Repeat_Type_Each_Weekday :: "each weekday"

// Allowed values for Create_Event_In_Scenario_Body.repeat_type.
Create_Event_In_Scenario_Body_Repeat_Type_Once :: "once"
Create_Event_In_Scenario_Body_Repeat_Type_Daily :: "daily"
Create_Event_In_Scenario_Body_Repeat_Type_Weekly :: "weekly"
Create_Event_In_Scenario_Body_Repeat_Type_Fortnightly :: "fortnightly"
Create_Event_In_Scenario_Body_Repeat_Type_Monthly :: "monthly"
Create_Event_In_Scenario_Body_Repeat_Type_Yearly :: "yearly"
Create_Event_In_Scenario_Body_Repeat_Type_Each_Weekday :: "each weekday"

// Allowed values for Create_Account_In_User_Body.type.
Create_Account_In_User_Body_Type_Bank :: "bank"
Create_Account_In_User_Body_Type_Credits :: "credits"
Create_Account_In_User_Body_Type_Cash :: "cash"
Create_Account_In_User_Body_Type_Loans :: "loans"
Create_Account_In_User_Body_Type_Mortgage :: "mortgage"
Create_Account_In_User_Body_Type_Stocks :: "stocks"
Create_Account_In_User_Body_Type_Vehicle :: "vehicle"
Create_Account_In_User_Body_Type_Property :: "property"
Create_Account_In_User_Body_Type_Insurance :: "insurance"
Create_Account_In_User_Body_Type_Other_Asset :: "other_asset"
Create_Account_In_User_Body_Type_Other_Liability :: "other_liability"

// Allowed values for Create_Category_In_User_Body.refund_behaviour.
Create_Category_In_User_Body_Refund_Behaviour_Debits_Are_Deductions :: "debits_are_deductions"
Create_Category_In_User_Body_Refund_Behaviour_Credits_Are_Refunds :: "credits_are_refunds"

